
import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "modern-normalize/modern-normalize.css";
import "./globals.css";
import { Roboto } from 'next/font/google';


import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import TanStackProvider from "@/components/TanStackProvider/TanStackProvider";
import AuthProvider from "@/components/AuthProvider/AuthProvider";

const roboto = Roboto({
  subsets: ['latin'], 
  weight: ['400', '700'],
  variable: '--font-roboto', 
  display: 'swap', 
});


export const metadata: Metadata = {
  title: "NoteHub - Your Personal Note Management App",
  description: "Generated by create next app",
  openGraph: {
    title: `NoteHub`,
    description: "Generated by create next app",
    url: `https://notehub.com/`,
    siteName: 'NoteHub',
    images: [
      {
        url: 'https://ac.goit.global/fullstack/react/notehub-og-meta.jpg',
        width: 1200,
        height: 630,
        alt: "NoteHub - Your Personal Note Management App",
      },
    ],
    type: 'article',
  },
};

export default function RootLayout({
  children,
  // modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.variable}>
      <TanStackProvider>
  <AuthProvider>
    <Header />
    {children}
    <Footer />
  </AuthProvider>
</TanStackProvider>
      </body>
    </html>
  );
}
